//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAY {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAY.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error importing image.
        /// </summary>
        internal static string ERROR_IMPORTING_IMAGE {
            get {
                return ResourceManager.GetString("ERROR_IMPORTING_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving.
        /// </summary>
        internal static string ERROR_SAVING {
            get {
                return ResourceManager.GetString("ERROR_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final text.
        /// </summary>
        internal static string FINAL_TEXT {
            get {
                return ResourceManager.GetString("FINAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LET2.IMG is missing.
        /// </summary>
        internal static string LET2_IMG_MISSING {
            get {
                return ResourceManager.GetString("LET2.IMG_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded.
        /// </summary>
        internal static string LOADED {
            get {
                return ResourceManager.GetString("LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RAY.XXX is missing.
        /// </summary>
        internal static string RAY_XXX_MISSING {
            get {
                return ResourceManager.GetString("RAY.XXX_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rayus.txt is missing.
        /// </summary>
        internal static string RAYUS_TXT_MISSING {
            get {
                return ResourceManager.GetString("RAYUS.TXT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart the application to apply the changes.
        /// </summary>
        internal static string RESTART_APP_TO_APPLY_CHANGES {
            get {
                return ResourceManager.GetString("RESTART_APP_TO_APPLY_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved.
        /// </summary>
        internal static string SAVED {
            get {
                return ResourceManager.GetString("SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SLES_000.49 is missing.
        /// </summary>
        internal static string SLES_000_49_MISSING {
            get {
                return ResourceManager.GetString("SLES_000.49_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source.
        /// </summary>
        internal static string SOURCE {
            get {
                return ResourceManager.GetString("SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are pending changes. Do you want to save?.
        /// </summary>
        internal static string THERE_ARE_PENDING_CHANGES_DO_YOU_WANT_TO_SAVE {
            get {
                return ResourceManager.GetString("THERE_ARE_PENDING_CHANGES_DO_YOU_WANT_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version {0}.
        /// </summary>
        internal static string VERSION_X {
            get {
                return ResourceManager.GetString("VERSION_X", resourceCulture);
            }
        }
    }
}
